version: '3.8'

services:
  web:
    build:
      context: .  # Uses the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specifies the Dockerfile name if it's not the default 'Dockerfile'
    ports:
      - "8000:8000"  # Maps port 8000 of the container to port 8000 on the host
    volumes:
      - .:/usr/src/app  # Mounts the current directory to the container's working directory
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application

